logging:
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

orchestrate:
  sources:
    bag:
      type: rest
      options:
        baseUrl: https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2
        headers:
          X-Api-Key: l7c065746c011c4fc68855ed94d567f2ce
        paths:
          AdresseerbaarObject: adresseerbareobjecten
          Nummeraanduiding: nummeraanduidingen

    brk:
      type: file
      options:
        dataPath: data/brk

    brp:
      type: rest
      options:
        baseUrl: https://imx.apps.digilab.network/haalcentraal/api/brp
        paths:
          Persoon: personen

    woz:
      type: file
      options:
        dataPath: data/woz
