objectTypes:
  Persoon:
    attributes:
      burgerservicenummer:
        type: String
        identifier: true
        cardinality: 1
      naam:
        type: String
        cardinality: 1
      geboortedatum:
        type: String
        cardinality: 1
      nummeraanduidingIdentificatie:
        type: String
        cardinality: 0..1
