lineageNameMapping:
  hasLineage: geregistreerdMet
  ObjectLineage: Registratie
  orchestratedDataElements: bestaatUit
  OrchestratedDataElements: GeorkestreerdGegeven
  SourceDataElement: Brongegeven
  ObjectReference: Object
  subject: onderwerp
  property: kenmerk
  value: waarde
  objectKey: identificatie
  objectType: type
  wasDerivedFrom: isAfgeleidVan

targetModel:
  loader: yaml
  location: config/fieldlab.yaml

sourceModels:
  bag:
    loader: yaml
    location: config/bag.yaml
  bri:
    loader: yaml
    location: config/bri.yaml
  brk:
    loader: yaml
    location: config/brk.yaml
  brp:
    loader: yaml
    location: config/brp.yaml
  woz:
    loader: yaml
    location: config/woz.yaml

sourceRelations:
  - sourceType: bri:NatuurlijkPersoon
    property:
      name: brpPersoon
      target: brp:Persoon
      cardinality: '1'
      inverseName: briPersoon
      inverseCardinality: '1'
      keyMapping:
        burgerservicenummer: burgerservicenummer

  - sourceType: brk:NatuurlijkPersoon
    property:
      name: geregistreerdPersoon
      target: brp:Persoon
      cardinality: '1'
      keyMapping:
        burgerservicenummer: bsn

  - sourceType: brk:ObjectlocatieBinnenland
    property:
      name: bagAdres
      target: bag:Nummeraanduiding
      cardinality: '1'
      inverseName: isAdresVan
      inverseCardinality: 0..*
      keyMapping:
        identificatie: adresgegevens

  - sourceType: brp:Persoon
    property:
      name: nummeraanduiding
      target: bag:Nummeraanduiding
      cardinality: 0..1
      inverseName: ingeschrevene
      inverseCardinality: 0..*
      keyMapping:
        identificatie: nummeraanduidingIdentificatie

  - sourceType: woz:WOZObject
    property:
      name: adresseerbaarObject
      target: bag:AdresseerbaarObject
      cardinality: '1'
      inverseName: wozObject
      inverseCardinality: 0..1
      keyMapping:
        identificatie: adresseerbaarObjectIdentificatie

objectTypeMappings:
  KadastraalOnroerendeZaak:
    - sourceRoot: brk:OnroerendeZaak
      propertyMappings:
        identificatie:
          pathMappings:
            path: identificatie
        eigenaar:
          pathMappings:
            path: zakelijkGerechtigden/geregistreerdPersoon/naam
        identificatieNummeraanduiding:
          pathMappings:
            path: locatie/betreft/bagAdres/identificatie
        identificatieAdresseerbaarObject:
          pathMappings:
            path: locatie/betreft/bagAdres/isHoofdadresVan/identificatie
        bewoner:
          pathMappings:
            path: locatie/betreft/bagAdres/ingeschrevene/naam
        wozWaarde:
          pathMappings:
            path: locatie/betreft/bagAdres/isHoofdadresVan/wozObject/waarde
          combiner:
            type: sum

  Woning:
    - sourceRoot: bag:Nummeraanduiding
      propertyMappings:
        identificatie:
          pathMappings:
            path: identificatie
        huisnummer:
          pathMappings:
            path: huisnummer
        postcode:
          pathMappings:
            path: postcode
        totaalinkomen:
          pathMappings:
            path: ingeschrevene/briPersoon/verzamelinkomen/waarde
          combiner:
            type: sum
        heeftWoonfunctie:
          pathMappings:
            path: isHoofdadresVan/gebruiksdoelen
            map:
              type: cel
              options:
                expr: '"woonfunctie" in result'
        maaktDeelUitVan:
          pathMappings:
            path: isAdresVan/locatie/heeft
        heeftBewoner:
          pathMappings:
            path: ingeschrevene
        heeftEigenaar:
          pathMappings:
            path: isAdresVan/locatie/heeft/zakelijkGerechtigden/geregistreerdPersoon

  Bewoner:
    - sourceRoot: brp:Persoon
      propertyMappings:
        bsn:
          pathMappings:
            path: burgerservicenummer
        naam:
          pathMappings:
            path: naam
        leeftijd:
          pathMappings:
            path: geboortedatum
            map:
              type: age
        inkomen:
          pathMappings:
            path: briPersoon/verzamelinkomen/waarde

  Eigenaar:
    - sourceRoot: brp:Persoon
      propertyMappings:
        bsn:
          pathMappings:
            path: burgerservicenummer
        naam:
          pathMappings:
            path: naam
