objectTypes:
  KadastraalOnroerendeZaak:
    attributes:
      identificatie:
        type: String
        identifier: true
        cardinality: 1
      eigenaar:
        type: String
        cardinality: 0..*
      identificatieNummeraanduiding:
        type: String
        cardinality: 0..*
      identificatieAdresseerbaarObject:
        type: String
        cardinality: 0..*
      bewoner:
        type: String
        cardinality: 0..*
      wozWaarde:
        type: Integer
        cardinality: 0..1

  Woning:
    attributes:
      identificatie:
        type: String
        identifier: true
        cardinality: 1
      huisnummer:
        type: Integer
        cardinality: 1
      postcode:
        type: String
        cardinality: 0..1
      totaalinkomen:
        type: Integer
        cardinality: 0..1
    relations:
      maaktDeelUitVan:
        target: KadastraalOnroerendeZaak
        cardinality: 0..*
      heeft:
        target: Bewoner
        cardinality: 0..*

  Bewoner:
    attributes:
      bsn:
        type: String
        identifier: true
        cardinality: 1
      naam:
        type: String
        cardinality: 1
      leeftijd:
        type: Integer
        cardinality: 1
      inkomen:
        type: Integer
        cardinality: 0..1
