objectTypes:
  KadastraalOnroerendeZaak:
    attributes:
      identificatie:
        type: String
        identifier: true
        cardinality: 1
      eigenaar:
        type: String
        cardinality: 0..*
      identificatieNummeraanduiding:
        type: String
        cardinality: 0..*
      identificatieAdresseerbaarObject:
        type: String
        cardinality: 0..*
      bewoner:
        type: String
        cardinality: 0..*
      wozWaarde:
        type: Integer
        cardinality: 0..1
