objectTypes:
  WOZObject:
    attributes:
      identificatie:
        type: String
        identifier: true
        cardinality: 1
      adresseerbaarObjectIdentificatie:
        type: String
        cardinality: 1
      waarde:
        type: Integer
        cardinality: 1
